-- ============================================================
-- VisionBoard Coach Nudges Schema (FEATURE 3)
-- Run in the Supabase SQL Editor any time. Idempotent — safe to re-run.
--
-- Purpose:
--   Stores proactive AI coach nudges generated by the
--   ai-coach-patterns Netlify scheduled function. Separate from
--   coachBrief (the daily morning brief) because nudges are
--   asynchronous: detected on the server, surfaced when the user
--   next opens the app, dismissed/acted/feedback'd individually.
--
-- Lifecycle of a nudge:
--   1. Server detects a pattern in the user's data, calls Anthropic,
--      INSERTs a row here with kind + body.
--   2. Server enqueues a corresponding push (notifications_queue)
--      tagged with the nudge id so the dispatcher can include a
--      deep-link payload.
--   3. Client reads via the useCoachNudges hook, surfaces in the
--      AI Coach panel.
--   4. User taps Dismiss / Act / Not useful — client PATCHes the row
--      with the corresponding timestamp + (optional) feedback text.
--   5. Future scheduled runs read recent_dismissed_topics from this
--      table so the same family of pattern doesn't re-fire.
--
-- Cooldown rules enforced server-side (not in this schema):
--   - same `family` ≥ 14 days
--   - max 3 unread per user at any time
--   - max 1 generated per user per day
-- ============================================================

create table if not exists coach_nudges (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  -- Pattern family — coarse bucket the cooldown checks against. The
  -- LLM picks one when generating. Open enum so we can add new
  -- families without a migration; the client only renders ones it
  -- knows about and shows the body for the rest.
  family        text not null,
  -- Specific identifier for THIS instance — derived from the data
  -- (e.g. "weekday_dip:t3:wed"). Lets us detect re-fires of the
  -- exact same condition vs a new instance of the same family.
  signature     text,
  -- Single-line headline for the nudge surface
  title         text not null,
  -- Body — 1-3 sentences, no markdown
  body          text not null,
  -- Suggested actions (verbs the user can tap). JSON array of
  --   { label, action, ...payload }
  -- where action is one of: 'navigate', 'log_tracker', 'open_modal',
  -- 'dismiss', etc. Mirrors the existing coachBrief.verbs shape.
  verbs         jsonb not null default '[]'::jsonb,
  -- Detected-at vs scheduled-for vs actual events. All nullable
  -- except detected_at because the row exists at detection time.
  detected_at   timestamptz not null default now(),
  scheduled_for timestamptz,
  -- Set when the dispatcher ships the corresponding push
  pushed_at     timestamptz,
  -- Set when the user has actually seen the nudge in-app
  seen_at       timestamptz,
  dismissed_at  timestamptz,
  acted_at      timestamptz,
  -- Optional free-text "why isn't this useful?" feedback
  feedback      text,
  -- Original snapshot trace for debugging
  snapshot_window_days int default 90
);

create index if not exists coach_nudges_user_unread_idx
  on coach_nudges (user_id, detected_at desc)
  where dismissed_at is null and acted_at is null;

-- For cooldown checks: "any nudge in family X within the last 14 days"
create index if not exists coach_nudges_user_family_idx
  on coach_nudges (user_id, family, detected_at desc);

-- ── RLS ────────────────────────────────────────────────────
alter table coach_nudges enable row level security;

-- Read own nudges
drop policy if exists "coach_nudges: own read" on coach_nudges;
create policy "coach_nudges: own read"
  on coach_nudges for select
  using (auth.uid() = user_id);

-- Update own nudges (dismissed_at, seen_at, acted_at, feedback) —
-- the client patches its own rows; server-only writes everything else.
drop policy if exists "coach_nudges: own update" on coach_nudges;
create policy "coach_nudges: own update"
  on coach_nudges for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- No client INSERT or DELETE — only the scheduled function
-- (running with the service role key) generates nudges. Prevents a
-- compromised client from spoofing nudges.
drop policy if exists "coach_nudges: no client insert" on coach_nudges;
create policy "coach_nudges: no client insert"
  on coach_nudges for insert
  to authenticated
  with check (false);

drop policy if exists "coach_nudges: no client delete" on coach_nudges;
create policy "coach_nudges: no client delete"
  on coach_nudges for delete
  to authenticated
  using (false);

-- ── Helper view: nudges the client should surface right now ──
-- Visible (not dismissed, not acted), most-recent first, capped to
-- the 5 newest so a backlog doesn't drown the panel.
create or replace view coach_nudges_active as
  select *
    from coach_nudges
   where dismissed_at is null
     and acted_at is null
   order by detected_at desc;

-- ============================================================
-- Done. Sprint 1b (ai-coach-patterns Netlify function) will be the
-- only writer. Until then this table sits empty and the client falls
-- back to the heuristic detector in src/lib/coach/patterns.js.
-- ============================================================
